/* LEVITEC SITE CONTROL - Backend v0.5.0 */
const SPREADSHEET_ID='1yAZj3KXPYerlOcZFs3hASbVTPbgAbEuPoK8HSEsDRBA';
const GOOGLE_CLIENT_ID='125715939878-v29u8atv0k8g6smekk6lfuhrtqob4c1b.apps.googleusercontent.com';
const FRONTEND_ORIGIN='https://dferrando-hue.github.io';
const APP={NAME:'LEVITEC SITE CONTROL',VERSION:'0.5.0',MESSAGE_SOURCE:'LEVITEC_SITE_CONTROL'};
const SHEETS={USERS:'USUARIOS',PROJECTS:'PROYECTOS',USER_PROJECT:'USUARIO_PROYECTO',ROLES:'ROLES',PERMISSIONS:'PERMISOS',ROLE_PERMISSION:'ROL_PERMISO',CONFIG:'CONFIG'};
function doGet(){return ContentService.createTextOutput(JSON.stringify({ok:true,app:APP.NAME,version:APP.VERSION})).setMimeType(ContentService.MimeType.JSON)}
function doPost(e){try{const p=getRequestParams_(e);const action=cleanText_(p.action);if(!action)return postMessageHtml_({ok:false,error:'ACTION_REQUIRED',message:'No se ha indicado ninguna acción.'},'error');switch(action){case'bootstrap':return postMessageHtml_(bootstrap_(p),'bootstrap');case'adminProjectsList':return postMessageHtml_(adminProjectsList_(p),'adminProjectsList');case'adminProjectCreate':return postMessageHtml_(adminProjectCreate_(p),'adminProjectCreate');case'adminProjectUpdate':return postMessageHtml_(adminProjectUpdate_(p),'adminProjectUpdate');default:return postMessageHtml_({ok:false,error:'UNKNOWN_ACTION',message:'La acción solicitada no existe.'},'error')}}catch(err){return postMessageHtml_({ok:false,error:'SERVER_ERROR',message:err&&err.message?err.message:String(err)},'error')}}
function bootstrap_(p){const s=requireAuthenticatedUser_(p,'CORE_VIEW');return{ok:true,app:{name:APP.NAME,version:APP.VERSION},user:{email:s.user.email,name:s.user.name||s.identity.name||s.user.email,role:s.user.role,discipline:s.user.discipline},projects:getUserProjects_(s.user.email,s.user.role),permissions:s.permissions,modules:buildModuleAccess_(s.permissions)}}
function requireAuthenticatedUser_(p,perm){const identity=verifyGoogleIdToken_(p.credential);const user=getUserProfile_(identity.email);if(!user)throw new Error('Tu cuenta no está autorizada en LEVITEC SITE CONTROL.');if(!isYes_(user.active))throw new Error('Tu usuario está desactivado.');const permissions=getUserPermissions_(user.role);if(perm&&!permissions.includes(perm))throw new Error('No tienes permiso para realizar esta acción.');return{identity,user,permissions}}
function verifyGoogleIdToken_(idToken){idToken=cleanText_(idToken);if(!idToken)throw new Error('Google ID token requerido.');const r=UrlFetchApp.fetch('https://oauth2.googleapis.com/tokeninfo?id_token='+encodeURIComponent(idToken),{method:'get',muteHttpExceptions:true});if(r.getResponseCode()!==200)throw new Error('El token de Google no es válido.');const p=JSON.parse(r.getContentText());if(cleanText_(p.aud)!==GOOGLE_CLIENT_ID)throw new Error('El token pertenece a otro cliente OAuth.');const iss=cleanText_(p.iss);if(iss!=='accounts.google.com'&&iss!=='https://accounts.google.com')throw new Error('Emisor del token no válido.');if(String(p.email_verified).toLowerCase()!=='true')throw new Error('El correo de Google no está verificado.');if(Number(p.exp||0)<=Math.floor(Date.now()/1000))throw new Error('El token de Google ha caducado.');return{email:cleanEmail_(p.email),name:cleanText_(p.name),picture:cleanText_(p.picture),subject:cleanText_(p.sub)}}
function getUserProfile_(email){email=cleanEmail_(email);const u=readTable_(SHEETS.USERS).find(r=>cleanEmail_(r.EMAIL)===email);if(!u)return null;return{email:cleanEmail_(u.EMAIL),name:cleanText_(u.NOMBRE),role:cleanKey_(u.ROL),discipline:cleanKey_(u.DISCIPLINA),active:u.ACTIVO}}
function getUserProjects_(email,role){email=cleanEmail_(email);role=cleanKey_(role);const active=readTable_(SHEETS.PROJECTS).filter(p=>cleanKey_(p.PROYECTO_ID)&&isYes_(p.ACTIVO)).map(p=>({id:cleanKey_(p.PROYECTO_ID),name:cleanText_(p.NOMBRE)||cleanKey_(p.PROYECTO_ID),campus:cleanText_(p.CAMPUS)}));if(role==='ADMIN')return active.map(p=>({...p,projectRole:'ADMIN'}));const map={};active.forEach(p=>map[p.id]=p);const out={};readTable_(SHEETS.USER_PROJECT).forEach(a=>{if(cleanEmail_(a.EMAIL)!==email||!isYes_(a.ACTIVO))return;const id=cleanKey_(a.PROYECTO_ID);if(!map[id])return;out[id]={...map[id],projectRole:cleanKey_(a.ROL_PROYECTO)||role}});return Object.values(out)}
function adminProjectsList_(p){requireAuthenticatedUser_(p,'ADMIN_PROJECTS');return{ok:true,projects:readTable_(SHEETS.PROJECTS).filter(r=>cleanKey_(r.PROYECTO_ID)).map(r=>({id:cleanKey_(r.PROYECTO_ID),name:cleanText_(r.NOMBRE),campus:cleanText_(r.CAMPUS),active:isYes_(r.ACTIVO)})).sort((a,b)=>a.id.localeCompare(b.id))}}
function adminProjectCreate_(p){requireAuthenticatedUser_(p,'ADMIN_PROJECTS');const x=parsePayload_(p.payload),id=cleanKey_(x.projectId),name=cleanText_(x.name)||id,campus=cleanText_(x.campus),active=x.active===false?'NO':'SI';if(!id)throw new Error('El ID del proyecto es obligatorio.');if(!/^[A-Z0-9_-]{2,30}$/.test(id))throw new Error('ID de proyecto no válido.');const sh=getSheet_(SHEETS.PROJECTS),d=sh.getDataRange().getDisplayValues();for(let i=1;i<d.length;i++)if(cleanKey_(d[i][0])===id)throw new Error('Ya existe un proyecto con ID '+id+'.');sh.appendRow([id,name,campus,active]);SpreadsheetApp.flush();return{ok:true,message:'Proyecto creado correctamente.',project:{id,name,campus,active:active==='SI'}}}
function adminProjectUpdate_(p){requireAuthenticatedUser_(p,'ADMIN_PROJECTS');const x=parsePayload_(p.payload),id=cleanKey_(x.projectId),name=cleanText_(x.name)||id,campus=cleanText_(x.campus),active=x.active===true?'SI':'NO';if(!id)throw new Error('El ID del proyecto es obligatorio.');const sh=getSheet_(SHEETS.PROJECTS),d=sh.getDataRange().getDisplayValues();let row=0;for(let i=1;i<d.length;i++)if(cleanKey_(d[i][0])===id){row=i+1;break}if(!row)throw new Error('No existe el proyecto '+id+'.');sh.getRange(row,2,1,3).setValues([[name,campus,active]]);SpreadsheetApp.flush();return{ok:true,message:'Proyecto actualizado correctamente.',project:{id,name,campus,active:active==='SI'}}}
function getUserPermissions_(role){role=cleanKey_(role);const out=[];readTable_(SHEETS.ROLE_PERMISSION).forEach(r=>{if(cleanKey_(r.ROL_ID)!==role||!isYes_(r.ACTIVO))return;const p=cleanKey_(r.PERMISO_ID);if(p)out.push(p)});return[...new Set(out)]}
function buildModuleAccess_(p){const h=x=>p.includes(x);return{site:h('SITE_VIEW'),equipment:h('EQUIPMENT_VIEW'),warehouse:h('WAREHOUSE_VIEW'),deliveries:h('DELIVERY_VIEW'),documents:h('RFI_CREATE')||h('RAMS_CREATE')||h('EPERMIT_CREATE'),mechanical:h('MECHANICAL_VIEW'),electrical:h('ELECTRICAL_VIEW'),admin:h('ADMIN_USERS')||h('ADMIN_PROJECTS')}}
function readTable_(name){const v=getSheet_(name).getDataRange().getDisplayValues();if(!v.length)return[];const h=v[0].map(cleanKey_),rows=[];for(let i=1;i<v.length;i++){if(v[i].every(x=>!cleanText_(x)))continue;const o={};h.forEach((k,j)=>{if(k)o[k]=v[i][j]});rows.push(o)}return rows}
function getRequestParams_(e){if(!e)return{};if(e.postData&&e.postData.type&&e.postData.type.includes('application/json'))return JSON.parse(e.postData.contents||'{}');return e.parameter||{}}
function parsePayload_(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(String(v))}catch(e){throw new Error('Payload no válido.')}}
function postMessageHtml_(payload,type){const p=JSON.stringify(payload).replace(/</g,'\\u003c').replace(/>/g,'\\u003e'),t=JSON.stringify(type||'response'),s=JSON.stringify(APP.MESSAGE_SOURCE),o=JSON.stringify(FRONTEND_ORIGIN);return HtmlService.createHtmlOutput(`<!doctype html><html><body><script>(function(){window.top.postMessage({source:${s},type:${t},payload:${p}},${o});})();<\/script></body></html>`).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function getDb_(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function getSheet_(name){const sh=getDb_().getSheetByName(name);if(!sh)throw new Error('No existe la hoja: '+name);return sh}
function cleanText_(v){return String(v==null?'':v).normalize('NFKC').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\u00A0/g,' ').trim()}
function cleanEmail_(v){return cleanText_(v).replace(/\s+/g,'').toLowerCase()}
function cleanKey_(v){return cleanText_(v).replace(/\s+/g,'').toUpperCase()}
function isYes_(v){return['SI','SÍ','YES','TRUE','1'].includes(cleanKey_(v))}
function testUserAccess(){const email='dferrando@levitec.es',user=getUserProfile_(email),permissions=user?getUserPermissions_(user.role):[],projects=user?getUserProjects_(email,user.role):[];Logger.log(JSON.stringify({user,projects,permissions},null,2))}
